name: Smoke Trigger

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image for Robot with Chrome
      run: docker build --rm -f "Dockerfile" -t gcrobot:qa .
    
    - name: Run the tests
      run: docker run --rm -v %cd%:/workspace:cached -w /workspace gcrobot:qa python3 -m robot -v docker:true -v site:www -v env:test01 -v browser:chrome -i docker --outputdir ./report ./
