name: Run Web Smoke Tests

on:
  [workflow_dispatch]

permissions:
  contents: read

jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
    - name: Download and install browser
      uses: browser-actions/setup-firefox@latest
    - run:  |
        firefox --version
        
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install Needed Libraries for the framework
      run: |
        python -m pip install --upgrade pip
        pip install -r ./tools/requirement_files/test_exec_req.txt
        
    - name: Install Chrome Webdriver
      run:  |
        webdrivermanager chrome
        
    - name: Run Web Smoke Tests
      run:  |
        robot  --include SmokeANDWeb -v site:www -v env:dev01 -v browser:firefox  --outputdir ./report ./
        
    - name: Uninstall Libraries
      run:  |
        pip uninstall -r ./tools/requirement_files/test_exec_req.txt
